### ISSUE TITLE
Getting CancelledError when using retry decorator

### ISSUE THREAD

**Issue by KishanKishore** [lxl0928/retrying_async#1]
I am using the ```retry``` decorator with an async method:
```
import asyncio

from retrying_async import retry


@retry(attempts='infinite', delay=3)
async def a():
    await b()
    while True:
        try:
            print("Hi")
            await asyncio.sleep(1)
        except Exception as exception:
            print(type(exception))
            print("Exception encountered")
            raise exception


async def b():
    print("hi")


if __name__ == "__main__":
    asyncio.run(a())

```

Getting this exception here: 
```
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
<class 'concurrent.futures._base.CancelledError'>
Exception encountered
```

Any suggestions here ? This does not happen if I remove the ```retry``` decorator.

**Comment by sivasai-quartic** [comment]
facing same issue + 1. any fix for this ?

**Comment by lxl0928** [comment]
> I am using the `retry` decorator with an async method:
> 
> ```
> import asyncio
> 
> from retrying_async import retry
> 
> 
> @retry(attempts='infinite', delay=3)
> async def a():
>     await b()
>     while True:
>         try:
>             print("Hi")
>             await asyncio.sleep(1)
>         except Exception as exception:
>             print(type(exception))
>             print("Exception encountered")
>             raise exception
> 
> 
> async def b():
>     print("hi")
> 
> 
> if __name__ == "__main__":
>     asyncio.run(a())
> ```
> 
> Getting this exception here:
> 
> ```
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> Hi
> <class 'concurrent.futures._base.CancelledError'>
> Exception encountered
> ```
> 
> Any suggestions here ? This does not happen if I remove the `retry` decorator.


Here's a parameter `timeout` that causes the problem. `timeout` default value is `30`.

Link1: [source code 1](https://github.com/lxl0928/retrying-async/blob/54eec24e4183b4ea31c0e133ed11ec0f0535a194/retrying_async.py#L47)

Link2: [source code 2](https://github.com/lxl0928/retrying-async/blob/54eec24e4183b4ea31c0e133ed11ec0f0535a194/retrying_async.py#L94)
